//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialGraph.DataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class user
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public user()
        {
            this.user1 = new HashSet<user>();
            this.user2 = new HashSet<user>();
            this.hobbie = new HashSet<hobbie>();
        }
    
        public System.Guid ID_User { get; set; }
        public string second_name { get; set; }
        public string first_name { get; set; }
        public string middle_name { get; set; }
        public System.DateTime birthday { get; set; }
        public System.Guid ID_Gender { get; set; }
        public Nullable<System.Guid> ID_Birthplace { get; set; }
        public Nullable<System.Guid> ID_Residence { get; set; }
        public string Phone { get; set; }
    
        public virtual gender gender { get; set; }
        public virtual locality locality { get; set; }
        public virtual locality locality1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<user> user2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<hobbie> hobbie { get; set; }
    }
}
